version: "3.3"
services:
  web:
    image: 'jormae/welfare-web:1.3.1'
    build: .
    ports:
      - 3000:3000
    restart: always
    #left -> local, right ->container
    #http://lcoalhost:8080 -p 8080:3000